### ISSUE TITLE
Error with array parameters

### ISSUE THREAD

**Issue by jchittoda** [intellij-solidity/intellij-solidity#177] opened 2019-01-14 14:50 UTC
Plugin showing error when the function of this type is defined in the contract.
```
    function setParameters(
        uint[11] calldata _params, //use array here due to stack too deep issue.
        address _voteOnBehalf
    )
```

Error:
```
'(', ';', <function call expression>, <function modifier>, '=', returns or '{' expected, got '('
```

**Comment by SerCeMan** [comment] 2019-01-14 22:40
Hey, @jchittoda!

Thank you for the report! The issue is fixed in https://github.com/intellij-solidity/intellij-solidity/commit/5d603b81b8429d80a61e489c5ddbe730e4a39334, and the fix will be released in the next version of the plugin. 

However, it would be great if you could build the latest version of the plugin from master to check if the issue is fully fixed for you!

**Closed by SerCeMan** 2019-01-14 22:40 UTC

**Comment by jchittoda** [comment] 2019-01-15 12:44
Found the same error reported in another project. As the plugin expects the argument name which is optional.
```
function methodName(address, uint256, bytes calldata _a) external view returns (bool abc) 
```

**Comment by jchittoda** [comment] 2019-01-15 12:45
Thanks @SerCeMan I will wait for the next build. Thanks for fixing this.
