### ISSUE TITLE
emit syntax

### ISSUE THREAD

**Issue by fredfortier** [intellij-solidity/intellij-solidity#71] opened 2018-04-21 04:13 UTC
Using `emit` (e.g. `emit Deposit(msg.sender, _id, msg.value);`) displays an error:

**Comment by SerCeMan** [comment] 2018-04-21 10:50
Hey, @fredfortier!

Closing this as a duplicate of https://github.com/intellij-solidity/intellij-solidity/issues/59

**Closed by SerCeMan** 2018-04-21 10:50 UTC
