### ISSUE TITLE
HELP! I really want to use it! 

### ISSUE THREAD

**Issue by dawnkie** [intellij-solidity/intellij-solidity#301] opened 2022-05-21 04:33 UTC
In IntelliJ, I've been installed `solidity-plugin` for a whole year, but I nerver know how to use it. I don't know how to config it -- I tried to download all kinds of ethereumJ, but I always got in trouble. I tried to find a document for configuration, nothing, I got nothing. I really want to use it, please give me a hit. (In the past year, I only know using `solidity-plugin`  for reading, this is all I know about, o(╥﹏╥)o)
![image](https://user-images.githubusercontent.com/47878132/169635479-6d59da7f-c64d-4b94-b82c-4bca5c897614.png)

**Comment by SerCeMan** [comment] 2022-05-21 09:57
Hi, @dawnkie! Unfortunately, EthereumJ is not supported anymore and can't be used. However, you can still use the plugin without running the contracts from IntelliJ. As for general workflow, this video tutorial might be useful – https://www.youtube.com/watch?v=7LCHlkdibWg, although please note that a lot of tooling has changed since 2017. 

I'll close this issue as a duplicate of https://github.com/intellij-solidity/intellij-solidity/issues/236.

**Closed by SerCeMan** 2022-05-21 09:57 UTC
