### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by ZitRos** [intellij-solidity/intellij-solidity#35] opened 2017-12-21 21:51 UTC
Hello! Thanks for an awesome plugin for Intellij!

I've found one syntax problem. While this code is valid and compiles well, it shows an error:

![2017-12-21_234728](https://user-images.githubusercontent.com/4989256/34276302-7880e836-e6a9-11e7-9fae-363a0b0574df.png)

I will be happy to help if you don't mind, just point me to a piece of source code to look at or DIY :) Thanks!

**Comment by SerCeMan** [comment] 2017-12-22 00:49
Hi, @ZitRos!

The problem is related to [the bnf grammar](https://github.com/intellij-solidity/intellij-solidity/blob/master/src/main/grammars/solidity.bnf) which is used to generate the parser. 

You can work on this grammar using the  [Grammar-Kit](https://github.com/JetBrains/Grammar-Kit) plugin. The first step might be to reproduce the problem. You can use "Live Preview" for that. Another tip is to use the structure view to see what actually was parsed.
![screen shot 2017-12-22 at 11 43 17 am](https://user-images.githubusercontent.com/1780970/34280652-61a96426-e70d-11e7-8055-455ac6139665.png)

You can play with grammar until the problem is fixed in the "Live Preview" and then write a test for the problem, `me.serce.solidity.lang.core.SolidityCompleteCustomParsingTest` is a good place to put such test. E.g. `testArrays()` test arrays and uses data: `src/test/resources/fixtures/parser/arrays.sol` as the source and `src/test/resources/fixtures/parser/arrays.txt` as the expected result. A successfully parsed code shouldn't contain any errors in the resulted AST. 

Note that once you changed the grammar, in order for tests to work, you need to regenerate the code by running `./gradlew lexer parser` (there is a run configuration called `lexer parser` exists).

Hope that helps. Feel free to ask more questions :)

**Comment by ZitRos** [comment] 2017-12-22 00:52
Thanks @SerCeMan for such detailed reply, I appreciate it! I will definitely take a look at this on the weekend. Have a good weekend to! :)

**Closed** 2017-12-25 09:12 UTC
