### ISSUE TITLE
Plugin reports not existing errors

### ISSUE THREAD

**Issue by banciur** [intellij-solidity/intellij-solidity#7] opened 2017-03-29 12:34 UTC
Hi, 
So I'm new to solidity and using your plugin just to browse but it reports errors in code that I know is correct. 
Attaching screen-shots:
![sol_plugin_error_1](https://cloud.githubusercontent.com/assets/5120930/24454569/9fb2f268-148c-11e7-80fb-59980f130348.png)

![sol_plugin_error_2](https://cloud.githubusercontent.com/assets/5120930/24454570/9fb371fc-148c-11e7-9791-7f167a2058d0.png)

**Comment by SerCeMan** [comment] 2017-03-29 13:20
Hey, @banciur!

Thanks for your report! The first problem was fixed on master. The second one is harder, I put a temporary fix, but `assembly` grammar requires more thoughtful approach.

I'm going to cut the release today, but the approval can take up to a week. In the meantime, you can build the plugin from sources and check if the issue is resolved.

Feel free to reopen the issue it hasn't been fixed.

**Closed by SerCeMan** 2017-03-29 13:20 UTC
Labels: bug

**Comment by banciur** [comment] 2017-03-29 13:43
Awesome, 
Thank man that was fast.
