### ISSUE TITLE
Project slow after adding heavy use of custom types

### ISSUE THREAD

**Issue by Lumyo** [intellij-solidity/intellij-solidity#351] opened 2023-03-14 14:21 UTC
I'm working on a pretty large project, where everything was fine until I recently updated my project to make heavy use of user defined value types ( https://blog.soliditylang.org/2021/09/27/user-defined-value-types/ ) and user defined operators ( https://blog.soliditylang.org/2023/02/22/user-defined-operators/ ) through use of the PRBMath library ( https://github.com/PaulRBerg/prb-math ).

Now, when using "Find usage" it takes something like 5-10 seconds to find all usages of a function. If I use a commit prior to those changes, it is instant.
Colors on text in the editor also take 5-10 seconds to appear when scrolling in a file

The commit at which the issue started consisted in modifying most of `uint256` used in the repo, by custom type `UD60x18`.
I assume the problem is somehow related to the heavy use of custom types as function input / outputs, because I've never experienced that before those changes.

I've tried to reproduce the issue with a small repo but without success

**Comment by SerCeMan** [comment] 2023-03-14 23:23
Hi, @Lumyo! Do you know if there is any way for me to reproduce the issue? If there is no way, then it'll be very hard to come up with a fix because resolving is likely to involve a lot of profiling.

**Comment by Lumyo** [comment] 2023-03-15 00:20
Hey @SerCeMan !
I cant share yet the repo, as code is still private, though it will be public at some point (Probably in ~2 months)
I'll try again to see if I can reproduce the issue in a new repo, otherwise I guess we'll have to wait until the repo is made public

**Comment by Lumyo** [comment] 2023-03-16 08:32
@SerCeMan I've tried to reproduce without success.
2 other devs from my team confirmed that the change created performance issues on their side too with the plugin (so it's not just something settings related on my side)

I've talked to my team and they are fine with me giving you access to the repo before we make it public. So I'm sending an invite your way. Just please make sure to not share code from there until it is made public.

The branch to look at is the branch `update-prb-math`, in particular the file `./contracts/pool/PoolInternal.sol` ( https://github.com/Premian-Labs/premia-v3-contracts-private/blob/update-prb-math/contracts/pool/PoolInternal.sol )

This is the commit where the issue starts : https://github.com/Premian-Labs/premia-v3-contracts-private/commit/52512a9aecb19084fa264ae0ccbccd03cea65bfe (Before that, no performance issue)

**Closed** 2023-04-01 11:30 UTC
