### ISSUE TITLE
Build error - compiler is 0.4.19?

### ISSUE THREAD

**Issue by nickjvandyke** [intellij-solidity/intellij-solidity#89] opened 2018-05-27 22:25 UTC
Getting my dev environment set up. Attempted to compile

```
pragma solidity ^0.4.24;

contract Solidity {
    function doesNothing() {

    }
}
```

and I got `Error:(1, 1) /home/nick/dev/ErectorCoin/solidity/src/Solidity.sol:1:1: Error: Source file requires different compiler version (current compiler is 0.4.19+commit.c4cbbb05.Linux.g++ - note that nightly builds are considered to be strictly less than the released version`

Changing to `pragma solidity ^0.4.19;` let me compile successfully.

As a result, I also can't use emit keyword, constructor keyword, etc. I checked other issues about `emit` causing build errors, and solutions were just ensuring that they had the latest plugin version.

I've checked my IntelliJ plugins and I have version 2.1.0 of the intellij-solidity plugin. Is there anything I can do? I do have solc 0.4.24 installed on my computer, if I'm able to instruct the plugin to use that.

While I'm at it, is there a way for me to use remapping arguments for the solc compiler? So that I can have `src` and `lib` directories on the same level. Currently I'm getting `file outside of allowed directories` when attempting to compile a contract in my `src` folder that's importing a contract from `lib` like `import "../lib/lib.sol";`

Thanks!

**Comment by NickvanDyke** [comment] 2018-05-28 19:46
I think it's related to installing and configuring the plugin to use ethereumj. Prior to doing so, attempting to compile a .sol file just copies it to the output directory (doesn't seem like the behavior I should be having?) But once I configure the plugin to use ethereumj, it gives me the compiler version error, and lowering the `pragma solidity` version allowing it to compile causes .abi and .bin files to be produced in the output directory as well. I also checked the `lib` folder in the ethereumj that the plugin downloads for you, and it has `solcJ-all-0.4.19.jar`, which corresponds with the `0.4.19` compiler version that I'm getting in the error.

**Comment by mbolotov** [comment] 2018-05-28 20:27
Hey, @NickvanDyke!

> I do have solc 0.4.24 installed on my computer, if I'm able to instruct the plugin to use that.
This feature is in the master branch now and will be released with the next plugin version

> is there a way for me to use remapping arguments for the solc compiler?
No, there is no such a way now. I had a thought to add this settings. The problem is that such a setting would look odd in the global settings. And it's a bit harder to insert one to the project's settings.

> I think it's related to installing and configuring the plugin to use ethereumj
You are right, the plugin extracts solc from the ethereumj bundle.

>which doesn't seem like the behavior I should be having?
Well, it's a kind of expected behavior. The default build process of a java project treats a solidity file as a resource and thus just copies it in the output folder. 

As a workaround to get your own version of solc on 2.1.0 plugin, you may just replace the solc executable inside the ethereumj bundle

**Comment by mbolotov** [comment] 2018-05-29 06:27
> No contract found in the path: Solidity  // Note that my solidity file was Solidity.sol

Any time I see it, I first try to ensure the compiled file is actually in place in the output directory (it's okay that message does not show the file extension)
You can try to call 'rebuild' action if you find no compiled files.
I'll try 0.4.23 as well - it might be some changes in solc behavior which breaks compiling via plugin.

>  Do you know when the next release will be?

Hey, @SerCeMan! Do you know when the next release will be?

**Comment by SerCeMan** [comment] 2018-05-29 10:11
Hey, @mbolotov, @NickvanDyke! 

I'm planning to release the new version somewhere this/next week, a few issues need to be fixed first.

**Closed as completed** 2024-05-15 13:41 UTC
