### ISSUE TITLE
Bug: invalid identifier expected inspection

### ISSUE THREAD

**Issue by bshevchenko** [intellij-solidity/intellij-solidity#6] opened 2017-03-27 22:24 UTC
![2017-03-28 1 23 15](https://cloud.githubusercontent.com/assets/1531049/24380660/319db890-1355-11e7-8f6e-a1841a3fb538.png)

Underlined by the red wavy line

**Comment by SerCeMan** [comment] 2017-03-28 14:41
Hey, @bshevchenko!

Thank you for the issue. It's fixed on master now. I'm going to cut the release tomorrow, but the approval can take up to a week. In the meantime, you can build the plugin from sources and check if the issue is resolved.

Feel free to reopen the issue if the problem hasn't been fixed :)

**Closed by SerCeMan** 2017-03-28 14:41 UTC

**Comment by bshevchenko** [comment] 2017-03-28 14:51
@SerCeMan thanks a lot! :)
