### ISSUE TITLE
Syntax highlight is completely broken

### ISSUE THREAD

**Issue by php4fan** [intellij-solidity/intellij-solidity#297] opened 2022-05-01 20:41 UTC
![image](https://user-images.githubusercontent.com/13969584/166163760-f139a90b-7696-4199-a54a-e97dd2096d84.png)

Look at the two strings that are not highlighted in green as strings (unlike the first one which is, as expected).

**Comment by php4fan** [comment] 2022-05-01 20:56
Also see this: https://youtrack.jetbrains.com/issue/WI-66479/Plugin's-Syntax-highlight-changes-after-deleting-and-re-typing-s

**Comment by php4fan** [comment] 2022-05-01 20:57
The highlight gets fixed if I delete and re-type the opening quote.

**Comment by mosinnik** [comment] 2022-05-08 00:40
I think duplicate https://github.com/intellij-solidity/intellij-solidity/issues/290

**Comment by SerCeMan** [comment] 2022-05-16 04:17
Thanks, I'll close this as a duplicate of https://github.com/intellij-solidity/intellij-solidity/issues/290. For the issue itself, I started looking into the issue but I haven't been able to figure out the right solution yet.

**Closed by SerCeMan** 2022-05-16 04:17 UTC
